/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tangbing_admin_myapplication_JNITest */

#ifndef _Included_com_tangbing_admin_myapplication_JNITest
#define _Included_com_tangbing_admin_myapplication_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tangbing_admin_myapplication_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tangbing_admin_myapplication_JNITest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
